name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: submodule init
      run: git submodule update --init

    - name: Install SFML dependencies
      run: sudo apt install libxrandr-dev libxcursor-dev libxi-dev libudev-dev libfreetype-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev libfreetype-dev

    - name: Build SFML from source
      run: |
        git clone https://github.com/SFML/SFML.git --branch 3.0.1
        mkdir SFML/build && cd SFML/build
        cmake ..
        make -j$(nproc)
        sudo make install

    - name: install asio
      run: sudo apt-get install libasio-dev

    - name: make
      run: cd src && make
